### ISSUE TITLE
is there comparisiong for slice vs netty ByteBuf vs nio ByteBuffer ?

### ISSUE THREAD

**Issue by wenweihu86** [airlift/slice#109]
is there comparision for slice vs netty ByteBuf ?

**Comment by debjitk** [comment]
The project seems to be dead. Me too needs some comparison.

**Comment by dain** [comment]
There are no benchmarks or comparisons to netty.  We orginally used the netty code but the netty code is designed for IO which made it harder for use as a generic memory abstraction.   Recently we decided to move Slice to be only backed by byte[] because that was the only large usage of slice.  I suggest you use move to the [Java Memory APIs ](https://openjdk.org/jeps/442) as a long term solution to raw memory acccess.
