### ISSUE TITLE
Add FNV hash functions

### ISSUE THREAD

**Issue by codope** [airlift/slice#114]
This is in pursuance of supporting FNV hash in [Presto](https://github.com/prestosql/presto).

**Comment by codope** [comment]
@martint Still waiting for the latest version of Slice to be released on [maven central](https://mvnrepository.com/artifact/io.airlift/slice). I need to add this functionality in Presto and its community version.

**Comment by widagdos** [comment]
https://github.com/airlift/slice/blob/95d5876d3f4c57321767113e97416a42bc41749a/src/main/java/io/airlift/slice/FnvHash.java#L33-L37

I think getByte should be replaced with getUnsignedByte. Otherwise when the byte value msb is set (the value is negative), there will be sign extension on the next line.
